# Learning Numpy

In [2]:
import numpy as np

In [112]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [113]:
arr = np.array([1,2,3,4],dtype='float')
arr

array([1., 2., 3., 4.])

In [114]:
arr[0] = 10.5
arr


array([10.5,  2. ,  3. ,  4. ])

In [115]:
arr.ndim

1

In [9]:
arr = np.array([[1,2],[3,4]],dtype='int16')
arr.ndim

2

In [11]:
arr.shape

(2, 2)

In [123]:
arr = np.array([[[1,2,1],[3,4,2]],[[5,6,4],[7,8,5]]],dtype='int16')
arr

# arr.shape

array([[[1, 2, 1],
        [3, 4, 2]],

       [[5, 6, 4],
        [7, 8, 5]]], dtype=int16)

In [19]:
arr.dtype

dtype('int16')

In [122]:
arr.itemsize

2

In [21]:
arr.size

12

In [22]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [124]:
arr = np.array([[1+2j],[9+6j]])
arr

array([[1.+2.j],
       [9.+6.j]])

In [24]:
arr= np.array([1,2,2],dtype='complex')
arr

array([1.+0.j, 2.+0.j, 2.+0.j])

In [25]:
arr.imag

array([0., 0., 0.])

In [26]:
arr.real


array([1., 2., 2.])

In [27]:
arr.imag= np.array([3,3,3])

In [28]:
arr

array([1.+3.j, 2.+3.j, 2.+3.j])

In [29]:
arr= np.array([1,2,0,0,0,0],dtype='bool')
arr

array([ True,  True, False, False, False, False])

In [33]:
arr=np.zeros((2,3,9))
arr

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [32]:
arr=np.ones((3,4))
arr


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
arr = np.empty((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [125]:
arr=np.full((2,3),1,dtype='int')
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [126]:
arr1=np.full_like(arr,5)
arr1

array([[5, 5, 5],
       [5, 5, 5]])

In [43]:
arr1=np.empty_like(arr)
arr1

array([[         0, 1074266112,          0],
       [1074266112,          0, 1074266112]])

In [44]:
np.random.rand(3,4)


array([[0.56524979, 0.87575486, 0.69926557, 0.24428158],
       [0.59842593, 0.38333247, 0.73530059, 0.73621897],
       [0.94282746, 0.22620763, 0.0899535 , 0.18606942]])

In [45]:
np.random.randint(1,9,(4,4))

array([[4, 1, 3, 2],
       [8, 6, 5, 6],
       [6, 8, 6, 3],
       [7, 8, 8, 3]])

In [127]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [129]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [133]:
np.linspace(1,40,4)

array([ 1., 14., 27., 40.])

In [52]:
marks = np.loadtxt('data.txt',skiprows=1)
print(marks)

[[ 34.  98.]
 [ 45.  90.]
 [ 56. 100.]]


In [135]:
marks.shape

(3, 2)

In [55]:
marks1,marks2=np.loadtxt('data.txt',skiprows=1,unpack=True)
marks1

array([34., 45., 56.])

In [56]:
marks2

array([ 98.,  90., 100.])

In [60]:
np.save('sample',np.array([1,2,3]))
np.load('sample.npy')

array([1, 2, 3])

In [141]:
np.fromfunction(lambda i,j: i+j,(2,8),dtype='int')

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [142]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,1,2,3]])
arr

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

In [144]:
arr[1,2]

9

In [145]:
arr= np.random.randint(1,9,(2,3,4))
arr

array([[[3, 2, 3, 1],
        [5, 3, 4, 6],
        [4, 6, 7, 7]],

       [[3, 4, 2, 1],
        [6, 1, 3, 4],
        [8, 8, 7, 3]]])

In [152]:
arr[1,1,0]

6

In [153]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [155]:
arr[:3]

array([1, 2, 3])

In [85]:
li = [1,2,3,4,5,6,7,8,9,10]
li_slice = li[0:5]

In [86]:
li_slice

[1, 2, 3, 4, 5]

In [87]:
li_slice[0]=99
print(li,"\n",li_slice)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
 [99, 2, 3, 4, 5]


In [89]:
arr_slice=arr[0:5]
arr_slice[0]=99

In [90]:
print(arr,"\n",arr_slice)


[99  2  3  4  5  6  7  8  9 10] 
 [99  2  3  4  5]


In [157]:
arr2=np.array([[1,2,3,4,5,6,7],[2,3,4,5,6,7,8],[3,4,5,6,7,8,9],[4,5,6,7,8,9,0]])
arr2

array([[1, 2, 3, 4, 5, 6, 7],
       [2, 3, 4, 5, 6, 7, 8],
       [3, 4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9, 0]])

In [192]:
arr2[:,::2]

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [3, 5, 7, 9],
       [4, 6, 8, 0]])

In [193]:
arr =np.array([1,2,3,4,5,6,7,8,9,0])
arr[np.array([1,3,5])]

array([2, 4, 6])

In [194]:
b=arr<5
# arr[arr<5]
arr[b]

array([1, 2, 3, 4, 0])

In [195]:
arr[0]=1

In [196]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [197]:
a1 = np.array([1,2,3,4,5])

In [198]:
a1

array([1, 2, 3, 4, 5])

In [199]:
a1.shape

(5,)

In [200]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2.shape


(2, 5)

In [201]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [202]:
a3=np.zeros((4,3,2))

In [203]:
a3


array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [206]:
a3[0,0,0]=1
a3[0,1,0]=1
a3[0,2,0]=1
a3[1,0,0]=1
a3[1,1,0]=1
a3[1,2,0]=1
a3[2,0,0]=1
a3[2,1,0]=1
a3[2,2,0]=1
a3[3,0,0]=1
a3[3,1,0]=1
a3[3,2,0]=1

a3[0,0,1]=0
a3[0,1,1]=0
a3[0,2,1]=0
a3[1,0,1]=0
a3[1,1,1]=0
a3[1,2,1]=0
a3[2,0,1]=0
a3[2,1,1]=0
a3[2,2,1]=0
a3[3,0,1]=0
a3[3,1,1]=0
a3[3,2,1]=0

In [207]:
a3

array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [212]:
a1

array([1, 2, 3, 4, 5])

In [213]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [214]:
a1+10

array([11, 12, 13, 14, 15])

In [215]:
a1*2

array([ 2,  4,  6,  8, 10])

In [216]:
a1**2

array([ 1,  4,  9, 16, 25])

In [217]:
a1/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [218]:
a1

array([1, 2, 3, 4, 5])

In [240]:
b1 = np.array([1,1,1,1,5])

In [230]:
b1

array([1, 1, 1, 1, 1])

In [221]:
a1+b1

array([2, 3, 4, 5, 6])

In [222]:
a1-b1

array([0, 1, 2, 3, 4])

In [223]:
a1/b1

array([1., 2., 3., 4., 5.])

In [224]:
b1.reshape

<function ndarray.reshape>

In [225]:
b1.shape

(5,)

In [227]:
b1.reshape(1,5)

array([[1, 1, 1, 1, 1]])

In [228]:
np.dot(a1,b1)

15

In [233]:
c=b1.reshape(5,1)

In [231]:
b1


array([1, 1, 1, 1, 1])

In [232]:
b1.shape

(5,)

In [234]:
c

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [235]:
c.shape

(5, 1)

In [236]:
b.shape

(10,)

In [237]:
b1

array([1, 1, 1, 1, 1])

In [238]:
b1.shape

(5,)

In [241]:
a1==b1

array([ True, False, False, False,  True])

In [244]:
np.logical_and(a1,b1)

array([ True,  True,  True,  True,  True])

In [245]:
a1

array([1, 2, 3, 4, 5])

In [246]:
b1

array([1, 1, 1, 1, 5])

In [247]:
c

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [248]:
c= np.array([0,0,0,0,0])

In [249]:
np.logical_and(a1,c)

array([False, False, False, False, False])

In [251]:
np.sum(a1)

15

In [252]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [253]:
np.exp(a1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [255]:
np.mean(a1)

3.0

In [258]:
np.median(b1)

1.0

In [259]:
np.std(b1)

1.6

In [260]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [261]:
np.sum(a2)

55

In [263]:
np.sum(a2,axis=1)

array([15, 40])

In [264]:
np.min(a2)

1

In [265]:
np.max(a2)

10

In [266]:
a1

array([1, 2, 3, 4, 5])

In [267]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [268]:
a3

array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [272]:
a= np.ones((5,2,1))
a

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [273]:
a.reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [274]:
a.reshape(1,2,5)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [276]:
a.reshape(2,5,1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [282]:
a = np.array([[1,2],[3,4]])
np.repeat(a,4,axis=1)

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [3, 3, 3, 3, 4, 4, 4, 4]])

In [283]:
a

array([[1, 2],
       [3, 4]])

In [285]:
a= np.array([1,1,1,1])
a


array([1, 1, 1, 1])

In [286]:
b= np.array([2,2,2,2])
b

array([2, 2, 2, 2])

In [291]:
np.vstack([a,b,a,a,b])

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [292]:
np.hstack([a,b])

array([1, 1, 1, 1, 2, 2, 2, 2])

In [293]:
a

array([1, 1, 1, 1])

In [294]:
a1

array([1, 2, 3, 4, 5])

In [295]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [296]:
np.hstack([a2,a2])

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])

In [297]:
np.vstack([a2,a2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [300]:
arr= np.zeros((4,1,3))
arr

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [299]:
np.squeeze(arr)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [302]:
brr=np.zeros((4,3,5))
brr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [306]:
np.expand_dims(brr,axis=(0,4)).shape

(1, 4, 3, 5, 1)

In [318]:
import time
a =np.random.rand(100000)
b= np.random.rand(100000)
start = time.time()
c = np.dot(a,b)
stop= time.time()
print("numpy",(stop-start)*1000)


numpy 1.0023117065429688


In [317]:
import time
a =np.random.rand(100000)
b= np.random.rand(100000)
start = time.time()
for i in range(10000):
    c += a[i]*b[i]
stop= time.time()
print("loop",(stop-start)*1000)

loop 10.972976684570312
